ARG IMAGE=intersystems/iris:2019.1.0S.111.0
ARG IMAGE=store/intersystems/iris-community:2019.3.0.309.0
FROM $IMAGE

USER root

WORKDIR /opt/irisapp
RUN chown ${ISC_PACKAGE_MGRUSER}:${ISC_PACKAGE_IRISGROUP} /opt/irisapp


USER irisowner

RUN mkdir -p /tmp/deps \

 && cd /tmp/deps \

 && wget -q https://pm.community.intersystems.com/packages/zpm/latest/installer -O zpm.xml


COPY  Installer.cls .
COPY  src src
COPY irissession.sh /

SHELL ["/irissession.sh"]

RUN \
  do $SYSTEM.OBJ.Load("Installer.cls", "ck") \
  Do $system.OBJ.Load("/tmp/deps/zpm.xml", "ck") \
  zpm "install webterminal" \
  set sc = ##class(App.Installer).setup() 


CMD [ "-l", "/usr/irissys/mgr/messages.log" ]